version: '3'
services:
        web:
                image: flask_port_v2
                build: .
                ports:
                        - "8097:8097"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
